---
- hosts: server
  remote_user: root
  become: yes
  tasks:
    - name: Update apt
      shell: sudo apt update
    - name: Install Docker
      apt:
        name:
          - docker
          - docker-compose
        state: present
    - name: Login DockerHub
      shell: docker login -u "{{DOCKER_USERNAME}}" -p "{{DOCKER_PASSWORD}}"
    - name: Copy file
      copy:
        src: docker-compose.yaml
        dest: /root
    - name: Restart docker-compose
      shell: |
          docker-compose stop
          docker-compose rm -f
          docker-compose pull
          docker-compose up -d
